### ISSUE TITLE
Load session should handle non-existant cookie file

### ISSUE THREAD

**Issue by muffinresearch** [kewisch/amolib#5]
See https://github.com/kewisch/amolib/blob/f9a1424c0240f419c9cedaf1c931e55508d50f98/src/session.js#L46

This function blows up if the file doesn't exist or if the file doesn't contain valid JSON.

**Comment by kewisch** [comment]
I fixed this in kewisch/mozblocklist@125de0f4814ab663e641e42e32dfe5514ef61e3e, it seems more favorable to have that method throw if something went wrong. Thanks for digging in!
